/** Demo strings for the internal /dev/ui component gallery (non-prod, noindex). */
export const devUi = {
  title: "Компоненты интерфейса",
  lead: "Внутренняя витрина дизайн-системы. Не индексируется и недоступна на проде.",
  sections: {
    type: "Типографика",
    colors: "Цвета",
    buttons: "Кнопки",
    fields: "Поля ввода",
    choice: "Выбор",
    disclosure: "Аккордеон и вкладки",
    overlays: "Окна и уведомления",
    media: "Логотип, кот, иконки",
    format: "Форматирование чисел",
    dark: "Тёмная тема",
  },
  sample: {
    display: "Одна комната — весь список покупок",
    h1: "Калькулятор ламината",
    h2: "Как посчитано",
    h3: "Подложка",
    body: "Ламинат укладывают рядами, обрезки длиннее 30 см переходят в следующий ряд.",
    small: "Длина комнаты",
    caption: "Проверено в ноябре 2026",
    result: "10",
    resultUnit: "пачек",
    quantity: "3 рулона",
  },
  buttons: {
    calculate: "Рассчитать ремонт",
    save: "Сохранить расчёт",
    copy: "Скопировать список",
    more: "Ещё параметры · 3",
    remove: "Удалить расчёт",
    saving: "Сохраняем",
    share: "Поделиться",
  },
  fields: {
    length: "Длина комнаты",
    width: "Ширина комнаты",
    unitM: "м",
    unitCm: "см",
    units: "Единицы",
    range: "От 0,5 до 30 м",
    required: "Введите длину",
    hint: "Измерьте по полу вдоль длинной стены",
    doors: "Двери",
    less: "Меньше",
    more: "Больше",
    roomType: "Тип помещения",
  },
  roomTypes: [
    { value: "living", label: "Жилая комната" },
    { value: "kitchen", label: "Кухня", description: "Плюс 5% на сложную геометрию" },
    { value: "bath", label: "Ванная" },
    { value: "corridor", label: "Коридор" },
  ],
  laying: {
    label: "Способ укладки",
    options: [
      { value: "straight", label: "Прямая" },
      { value: "diagonal", label: "Диагональ" },
      { value: "herringbone", label: "Ёлочка" },
    ],
  },
  shape: {
    label: "Форма комнаты",
    options: [
      { value: "rect", title: "Прямоугольная", description: "Четыре стены" },
      { value: "l", title: "Г-образная", description: "С выступом или нишей" },
    ],
  },
  presets: {
    label: "Типовые комнаты",
    chips: [
      { value: "kitchen", label: "Кухня 9 м²" },
      { value: "room", label: "Комната 18 м²" },
      { value: "hall", label: "Зал 24 м²" },
      { value: "bath", label: "Ванная 4 м²" },
    ],
  },
  accordion: [
    { value: "how", title: "Как посчитано", text: "Площадь 4,6 × 4,3 = 19,8 м², плюс 7% на подрезку." },
    { value: "source", title: "Откуда норма", text: "Инструкция производителя, проверено в ноябре 2026." },
  ],
  tabs: [
    { value: "list", label: "Список", text: "Ламинат, подложка, плинтус." },
    { value: "scheme", label: "Схема", text: "Раскладка рядами." },
  ],
  overlays: {
    openDialog: "Открыть окно",
    openSheet: "Открыть шторку",
    toast: "Показать уведомление",
    toastText: "Ссылка скопирована",
    dialogTitle: "Удалить расчёт?",
    dialogText: "Расчёт пропадёт из «Моих расчётов».",
    sheetTitle: "Ещё параметры",
    close: "Закрыть",
    cancel: "Отмена",
  },
  media: {
    mascotHello: "Кот Умняут машет лапой",
    materials: { laminate: "Ламинат", wallpaper: "Обои", "tile-adhesive": "Плиточный клей" },
    noPhoto: "Подложка",
  },
} as const;
