#!/usr/bin/env node
// Mascot image pipeline (design system: mascot; plan P3.7).
//   pnpm --filter web images        → rebuild public/img/mascot + src/shared/config/mascot.gen.ts
//   pnpm --filter web images:check  → CI: sources unchanged since the last build, files exist, weight budgets hold
// Outputs are committed: encoders differ slightly between platforms, so CI checks inputs and budgets, not bytes.
import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = join(dirname(fileURLToPath(import.meta.url)), "../../..");
const web = join(root, "apps/web");
const outDir = join(web, "public/img/mascot");
const manifestPath = join(web, "src/shared/config/mascot.gen.ts");
const ENCODER = { avif: { quality: 50, effort: 6 }, webp: { quality: 80, alphaQuality: 85, effort: 6 } };
const ALPHA_FLOOR = 24; // alpha below this is generation noise around the character

/**
 * Stage-1 poses: source, rendered CSS widths (1× and 2× are built), budget per AVIF file in KB.
 * AVIF is what browsers download; WebP is the fallback for old ones and may weigh up to 2× the budget.
 */
const POSES = {
  hello: { source: "Cheerful Cat Mascot with Blueprint.png", widths: [160, 400], budgetKb: 60 },
  done: { source: "Winking Cat Mascot with Calculator and Thumbs-Up.png", widths: [56, 96], budgetKb: 10 },
  warn: { source: "Friendly Orange Tabby Mascot with Raised Paw.png", widths: [56, 96], budgetKb: 10, avifQuality: 45 },
  oops: { source: "Apologetic Tabby Cat Shrugging.png", widths: [160, 240], budgetKb: 40 },
  head: { source: "Cute Orange Tabby Cat Avatar.png", widths: [40], budgetKb: 4 },
};

const sha = (buffer) => createHash("sha256").update(buffer).digest("hex");
const configHash = sha(Buffer.from(JSON.stringify({ POSES, ENCODER, ALPHA_FLOOR }))).slice(0, 12);

/** Clears faint alpha and crops to the visible character. */
async function prepare(input) {
  const { data, info } = await sharp(input).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  let [left, top, right, bottom] = [info.width, info.height, -1, -1];
  for (let y = 0; y < info.height; y++) {
    for (let x = 0; x < info.width; x++) {
      const a = (y * info.width + x) * 4 + 3;
      if (data[a] < ALPHA_FLOOR) {
        data[a] = 0;
        continue;
      }
      if (x < left) left = x;
      if (x > right) right = x;
      if (y < top) top = y;
      if (y > bottom) bottom = y;
    }
  }
  const width = right - left + 1;
  const height = bottom - top + 1;
  const png = await sharp(data, { raw: info }).extract({ left, top, width, height }).png().toBuffer();
  return { png, width, height };
}

async function build() {
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });
  const manifest = {};
  for (const [pose, { source, widths, avifQuality }] of Object.entries(POSES)) {
    const input = await readFile(join(root, "docs/details", source));
    const { png, width, height } = await prepare(input);
    const sizes = [...new Set(widths.flatMap((w) => [w, w * 2]))].sort((a, b) => a - b);
    const entry = { width, height, sourceSha: sha(input).slice(0, 16), avif: [], webp: [] };
    for (const w of sizes) {
      for (const format of ["avif", "webp"]) {
        const options = format === "avif" && avifQuality ? { ...ENCODER.avif, quality: avifQuality } : ENCODER[format];
        const file = await sharp(png).resize({ width: w })[format](options).toBuffer();
        const name = `${pose}-${w}.${sha(file).slice(0, 8)}.${format}`;
        await writeFile(join(outDir, name), file);
        entry[format].push({ w, src: `/img/mascot/${name}` });
      }
    }
    manifest[pose] = entry;
    console.log(`${pose}: ${width}×${height} → ${sizes.join(", ")}`);
  }
  const body = `// Generated by apps/web/scripts/images.mjs (config ${configHash}). Do not edit.\nexport const mascotImages = ${JSON.stringify(manifest, null, 2)} as const;\n`;
  await writeFile(manifestPath, body);
  console.log(`wrote ${relative(root, manifestPath)}`);
}

async function check() {
  const errors = [];
  const text = await readFile(manifestPath, "utf8").catch(() => "");
  if (!text.includes(`(config ${configHash})`)) errors.push("pipeline config changed — run `pnpm --filter web images`");
  const manifest = JSON.parse(text.slice(text.indexOf("{"), text.lastIndexOf("}") + 1) || "{}");
  const listed = new Set();
  for (const [pose, { source, budgetKb }] of Object.entries(POSES)) {
    const entry = manifest[pose];
    if (!entry) {
      errors.push(`${pose}: missing from manifest`);
      continue;
    }
    const input = await readFile(join(root, "docs/details", source));
    if (sha(input).slice(0, 16) !== entry.sourceSha) errors.push(`${pose}: source changed — rebuild images`);
    for (const [format, limitKb] of [
      ["avif", budgetKb],
      ["webp", budgetKb * 2],
    ]) {
      for (const { src } of entry[format]) {
        listed.add(src.split("/").pop());
        const size = await stat(join(web, "public", src)).then(
          (s) => s.size,
          () => -1,
        );
        if (size < 0) errors.push(`${src}: file missing`);
        else if (size > limitKb * 1024) errors.push(`${src}: ${(size / 1024).toFixed(1)} KB > ${limitKb} KB budget`);
      }
    }
  }
  for (const name of await readdir(outDir).catch(() => [])) {
    if (!listed.has(name)) errors.push(`public/img/mascot/${name}: not in manifest`);
  }
  if (errors.length) {
    console.error(`Image check failed:\n${errors.map((e) => `  ✗ ${e}`).join("\n")}`);
    process.exit(1);
  }
  console.log("Image check passed.");
}

await (process.argv.includes("--check") ? check() : build());
