// Generated by apps/web/scripts/images.mjs (config 3d980fbbe068). Do not edit.
export const mascotImages = {
  "hello": {
    "width": 923,
    "height": 1134,
    "sourceSha": "7b6fed00fef7fa78",
    "avif": [
      {
        "w": 160,
        "src": "/img/mascot/hello-160.0e0112d9.avif"
      },
      {
        "w": 320,
        "src": "/img/mascot/hello-320.3d6edca8.avif"
      },
      {
        "w": 400,
        "src": "/img/mascot/hello-400.12c26526.avif"
      },
      {
        "w": 800,
        "src": "/img/mascot/hello-800.ed8c1525.avif"
      }
    ],
    "webp": [
      {
        "w": 160,
        "src": "/img/mascot/hello-160.4bc68386.webp"
      },
      {
        "w": 320,
        "src": "/img/mascot/hello-320.6a9f3345.webp"
      },
      {
        "w": 400,
        "src": "/img/mascot/hello-400.ba8356fe.webp"
      },
      {
        "w": 800,
        "src": "/img/mascot/hello-800.1e06b2f7.webp"
      }
    ]
  },
  "done": {
    "width": 971,
    "height": 1147,
    "sourceSha": "d02e7f5aa7d48058",
    "avif": [
      {
        "w": 56,
        "src": "/img/mascot/done-56.09aa5fd6.avif"
      },
      {
        "w": 96,
        "src": "/img/mascot/done-96.5130f8be.avif"
      },
      {
        "w": 112,
        "src": "/img/mascot/done-112.5694c5fe.avif"
      },
      {
        "w": 192,
        "src": "/img/mascot/done-192.29b3852f.avif"
      }
    ],
    "webp": [
      {
        "w": 56,
        "src": "/img/mascot/done-56.f49a53a8.webp"
      },
      {
        "w": 96,
        "src": "/img/mascot/done-96.748155e6.webp"
      },
      {
        "w": 112,
        "src": "/img/mascot/done-112.637e87b2.webp"
      },
      {
        "w": 192,
        "src": "/img/mascot/done-192.678bc701.webp"
      }
    ]
  },
  "warn": {
    "width": 748,
    "height": 1183,
    "sourceSha": "a370885728a583f7",
    "avif": [
      {
        "w": 56,
        "src": "/img/mascot/warn-56.c95c3ff3.avif"
      },
      {
        "w": 96,
        "src": "/img/mascot/warn-96.b86e96cf.avif"
      },
      {
        "w": 112,
        "src": "/img/mascot/warn-112.011cd643.avif"
      },
      {
        "w": 192,
        "src": "/img/mascot/warn-192.c6fdabbc.avif"
      }
    ],
    "webp": [
      {
        "w": 56,
        "src": "/img/mascot/warn-56.3f828132.webp"
      },
      {
        "w": 96,
        "src": "/img/mascot/warn-96.bbff099a.webp"
      },
      {
        "w": 112,
        "src": "/img/mascot/warn-112.54ea4b2e.webp"
      },
      {
        "w": 192,
        "src": "/img/mascot/warn-192.7ea2153c.webp"
      }
    ]
  },
  "oops": {
    "width": 816,
    "height": 1115,
    "sourceSha": "cdbb54d908e0662c",
    "avif": [
      {
        "w": 160,
        "src": "/img/mascot/oops-160.8ef27431.avif"
      },
      {
        "w": 240,
        "src": "/img/mascot/oops-240.1fd917a1.avif"
      },
      {
        "w": 320,
        "src": "/img/mascot/oops-320.80614254.avif"
      },
      {
        "w": 480,
        "src": "/img/mascot/oops-480.1092cb8a.avif"
      }
    ],
    "webp": [
      {
        "w": 160,
        "src": "/img/mascot/oops-160.4bdc3f55.webp"
      },
      {
        "w": 240,
        "src": "/img/mascot/oops-240.7538e571.webp"
      },
      {
        "w": 320,
        "src": "/img/mascot/oops-320.29b678c6.webp"
      },
      {
        "w": 480,
        "src": "/img/mascot/oops-480.dabf1fc1.webp"
      }
    ]
  },
  "head": {
    "width": 1253,
    "height": 993,
    "sourceSha": "77c9f1ebcd895908",
    "avif": [
      {
        "w": 40,
        "src": "/img/mascot/head-40.2495837a.avif"
      },
      {
        "w": 80,
        "src": "/img/mascot/head-80.2f8e15db.avif"
      }
    ],
    "webp": [
      {
        "w": 40,
        "src": "/img/mascot/head-40.7b778bb6.webp"
      },
      {
        "w": 80,
        "src": "/img/mascot/head-80.0f1d67be.webp"
      }
    ]
  }
} as const;
