// Generated by apps/web/scripts/images.mjs (config d4b7f13af936). Do not edit.
export const materialImages = {
  "laminate": {
    "width": 1342,
    "height": 1342,
    "sourceSha": "e90c1cc83a387a74",
    "avif": [
      {
        "w": 64,
        "src": "/img/m/laminate-64.a4989995.avif"
      },
      {
        "w": 96,
        "src": "/img/m/laminate-96.35e675b1.avif"
      },
      {
        "w": 128,
        "src": "/img/m/laminate-128.88745ee8.avif"
      },
      {
        "w": 192,
        "src": "/img/m/laminate-192.4d9122d8.avif"
      }
    ],
    "webp": [
      {
        "w": 64,
        "src": "/img/m/laminate-64.fc465978.webp"
      },
      {
        "w": 96,
        "src": "/img/m/laminate-96.3bf3df67.webp"
      },
      {
        "w": 128,
        "src": "/img/m/laminate-128.ad7c4174.webp"
      },
      {
        "w": 192,
        "src": "/img/m/laminate-192.208d2372.webp"
      }
    ]
  },
  "wallpaper": {
    "width": 1336,
    "height": 1336,
    "sourceSha": "8fb3c95ecc67cf80",
    "avif": [
      {
        "w": 64,
        "src": "/img/m/wallpaper-64.31cda7c3.avif"
      },
      {
        "w": 96,
        "src": "/img/m/wallpaper-96.020ec1ea.avif"
      },
      {
        "w": 128,
        "src": "/img/m/wallpaper-128.2c098318.avif"
      },
      {
        "w": 192,
        "src": "/img/m/wallpaper-192.95a498b5.avif"
      }
    ],
    "webp": [
      {
        "w": 64,
        "src": "/img/m/wallpaper-64.531b92f3.webp"
      },
      {
        "w": 96,
        "src": "/img/m/wallpaper-96.bfbe5c8d.webp"
      },
      {
        "w": 128,
        "src": "/img/m/wallpaper-128.8e87404a.webp"
      },
      {
        "w": 192,
        "src": "/img/m/wallpaper-192.c35c62f8.webp"
      }
    ]
  },
  "tile-adhesive": {
    "width": 1369,
    "height": 1369,
    "sourceSha": "47b359213822376e",
    "avif": [
      {
        "w": 64,
        "src": "/img/m/tile-adhesive-64.acbb8d19.avif"
      },
      {
        "w": 96,
        "src": "/img/m/tile-adhesive-96.227848f1.avif"
      },
      {
        "w": 128,
        "src": "/img/m/tile-adhesive-128.d71b325a.avif"
      },
      {
        "w": 192,
        "src": "/img/m/tile-adhesive-192.b7e14cd5.avif"
      }
    ],
    "webp": [
      {
        "w": 64,
        "src": "/img/m/tile-adhesive-64.58fff2f9.webp"
      },
      {
        "w": 96,
        "src": "/img/m/tile-adhesive-96.5f071384.webp"
      },
      {
        "w": 128,
        "src": "/img/m/tile-adhesive-128.3c61fa31.webp"
      },
      {
        "w": 192,
        "src": "/img/m/tile-adhesive-192.3356dbde.webp"
      }
    ]
  }
} as const;
