// Generated by apps/web/scripts/images.mjs (config 6d99f9bec5c5). Do not edit.
export const materialImages = {
  "laminate": {
    "width": 1342,
    "height": 1342,
    "sourceSha": "e90c1cc83a387a74",
    "avif": [
      {
        "w": 64,
        "src": "/img/m/laminate-64.a4989995.avif"
      },
      {
        "w": 96,
        "src": "/img/m/laminate-96.35e675b1.avif"
      },
      {
        "w": 128,
        "src": "/img/m/laminate-128.88745ee8.avif"
      },
      {
        "w": 192,
        "src": "/img/m/laminate-192.4d9122d8.avif"
      }
    ],
    "webp": [
      {
        "w": 64,
        "src": "/img/m/laminate-64.fc465978.webp"
      },
      {
        "w": 96,
        "src": "/img/m/laminate-96.3bf3df67.webp"
      },
      {
        "w": 128,
        "src": "/img/m/laminate-128.ad7c4174.webp"
      },
      {
        "w": 192,
        "src": "/img/m/laminate-192.208d2372.webp"
      }
    ]
  },
  "wallpaper": {
    "width": 1336,
    "height": 1336,
    "sourceSha": "8fb3c95ecc67cf80",
    "avif": [
      {
        "w": 64,
        "src": "/img/m/wallpaper-64.31cda7c3.avif"
      },
      {
        "w": 96,
        "src": "/img/m/wallpaper-96.020ec1ea.avif"
      },
      {
        "w": 128,
        "src": "/img/m/wallpaper-128.2c098318.avif"
      },
      {
        "w": 192,
        "src": "/img/m/wallpaper-192.95a498b5.avif"
      }
    ],
    "webp": [
      {
        "w": 64,
        "src": "/img/m/wallpaper-64.531b92f3.webp"
      },
      {
        "w": 96,
        "src": "/img/m/wallpaper-96.bfbe5c8d.webp"
      },
      {
        "w": 128,
        "src": "/img/m/wallpaper-128.8e87404a.webp"
      },
      {
        "w": 192,
        "src": "/img/m/wallpaper-192.c35c62f8.webp"
      }
    ]
  },
  "tile-adhesive": {
    "width": 1369,
    "height": 1369,
    "sourceSha": "47b359213822376e",
    "avif": [
      {
        "w": 64,
        "src": "/img/m/tile-adhesive-64.acbb8d19.avif"
      },
      {
        "w": 96,
        "src": "/img/m/tile-adhesive-96.227848f1.avif"
      },
      {
        "w": 128,
        "src": "/img/m/tile-adhesive-128.d71b325a.avif"
      },
      {
        "w": 192,
        "src": "/img/m/tile-adhesive-192.b7e14cd5.avif"
      }
    ],
    "webp": [
      {
        "w": 64,
        "src": "/img/m/tile-adhesive-64.58fff2f9.webp"
      },
      {
        "w": 96,
        "src": "/img/m/tile-adhesive-96.5f071384.webp"
      },
      {
        "w": 128,
        "src": "/img/m/tile-adhesive-128.3c61fa31.webp"
      },
      {
        "w": 192,
        "src": "/img/m/tile-adhesive-192.3356dbde.webp"
      }
    ]
  },
  "wallpaper-glue": {
    "width": 1236,
    "height": 1236,
    "sourceSha": "960b2d875db27d4b",
    "avif": [
      {
        "w": 64,
        "src": "/img/m/wallpaper-glue-64.abc4b004.avif"
      },
      {
        "w": 96,
        "src": "/img/m/wallpaper-glue-96.db92c10f.avif"
      },
      {
        "w": 128,
        "src": "/img/m/wallpaper-glue-128.24b28f99.avif"
      },
      {
        "w": 192,
        "src": "/img/m/wallpaper-glue-192.61dfa49e.avif"
      }
    ],
    "webp": [
      {
        "w": 64,
        "src": "/img/m/wallpaper-glue-64.dab70673.webp"
      },
      {
        "w": 96,
        "src": "/img/m/wallpaper-glue-96.3bf1d152.webp"
      },
      {
        "w": 128,
        "src": "/img/m/wallpaper-glue-128.8895e326.webp"
      },
      {
        "w": 192,
        "src": "/img/m/wallpaper-glue-192.6e592581.webp"
      }
    ]
  },
  "paint": {
    "width": 1283,
    "height": 1283,
    "sourceSha": "f4f18951925920f8",
    "avif": [
      {
        "w": 64,
        "src": "/img/m/paint-64.78472852.avif"
      },
      {
        "w": 96,
        "src": "/img/m/paint-96.4824c4c2.avif"
      },
      {
        "w": 128,
        "src": "/img/m/paint-128.745e64b5.avif"
      },
      {
        "w": 192,
        "src": "/img/m/paint-192.015175bc.avif"
      }
    ],
    "webp": [
      {
        "w": 64,
        "src": "/img/m/paint-64.9473df3b.webp"
      },
      {
        "w": 96,
        "src": "/img/m/paint-96.6428c9f5.webp"
      },
      {
        "w": 128,
        "src": "/img/m/paint-128.1daac23d.webp"
      },
      {
        "w": 192,
        "src": "/img/m/paint-192.bce8b690.webp"
      }
    ]
  },
  "primer": {
    "width": 1305,
    "height": 1305,
    "sourceSha": "03b87f0dc481879e",
    "avif": [
      {
        "w": 64,
        "src": "/img/m/primer-64.3183199b.avif"
      },
      {
        "w": 96,
        "src": "/img/m/primer-96.161c2f93.avif"
      },
      {
        "w": 128,
        "src": "/img/m/primer-128.2a74509f.avif"
      },
      {
        "w": 192,
        "src": "/img/m/primer-192.b771e90a.avif"
      }
    ],
    "webp": [
      {
        "w": 64,
        "src": "/img/m/primer-64.e2f04a12.webp"
      },
      {
        "w": 96,
        "src": "/img/m/primer-96.4a0844c6.webp"
      },
      {
        "w": 128,
        "src": "/img/m/primer-128.5b529c23.webp"
      },
      {
        "w": 192,
        "src": "/img/m/primer-192.a6f8f27e.webp"
      }
    ]
  },
  "underlay": {
    "width": 1368,
    "height": 1368,
    "sourceSha": "3125df64029c3d80",
    "avif": [
      {
        "w": 64,
        "src": "/img/m/underlay-64.248d8da8.avif"
      },
      {
        "w": 96,
        "src": "/img/m/underlay-96.0920a0c0.avif"
      },
      {
        "w": 128,
        "src": "/img/m/underlay-128.5c94acb7.avif"
      },
      {
        "w": 192,
        "src": "/img/m/underlay-192.ec9ba626.avif"
      }
    ],
    "webp": [
      {
        "w": 64,
        "src": "/img/m/underlay-64.6a133fc4.webp"
      },
      {
        "w": 96,
        "src": "/img/m/underlay-96.8ec1bef3.webp"
      },
      {
        "w": 128,
        "src": "/img/m/underlay-128.a53a6ad6.webp"
      },
      {
        "w": 192,
        "src": "/img/m/underlay-192.8e627e63.webp"
      }
    ]
  },
  "plinth": {
    "width": 1320,
    "height": 1320,
    "sourceSha": "44fa15c0c0bbeebb",
    "avif": [
      {
        "w": 64,
        "src": "/img/m/plinth-64.38b5367b.avif"
      },
      {
        "w": 96,
        "src": "/img/m/plinth-96.e14754d8.avif"
      },
      {
        "w": 128,
        "src": "/img/m/plinth-128.2e32fe03.avif"
      },
      {
        "w": 192,
        "src": "/img/m/plinth-192.4294e502.avif"
      }
    ],
    "webp": [
      {
        "w": 64,
        "src": "/img/m/plinth-64.6f32c015.webp"
      },
      {
        "w": 96,
        "src": "/img/m/plinth-96.abf30812.webp"
      },
      {
        "w": 128,
        "src": "/img/m/plinth-128.43fd5c8b.webp"
      },
      {
        "w": 192,
        "src": "/img/m/plinth-192.3c868ded.webp"
      }
    ]
  },
  "plinth-fittings": {
    "width": 1265,
    "height": 1265,
    "sourceSha": "ea4f744bcf71e2e3",
    "avif": [
      {
        "w": 64,
        "src": "/img/m/plinth-fittings-64.9642d0a6.avif"
      },
      {
        "w": 96,
        "src": "/img/m/plinth-fittings-96.00ea1c05.avif"
      },
      {
        "w": 128,
        "src": "/img/m/plinth-fittings-128.0beea29d.avif"
      },
      {
        "w": 192,
        "src": "/img/m/plinth-fittings-192.738864e1.avif"
      }
    ],
    "webp": [
      {
        "w": 64,
        "src": "/img/m/plinth-fittings-64.dad42197.webp"
      },
      {
        "w": 96,
        "src": "/img/m/plinth-fittings-96.5b5da494.webp"
      },
      {
        "w": 128,
        "src": "/img/m/plinth-fittings-128.1d4164b0.webp"
      },
      {
        "w": 192,
        "src": "/img/m/plinth-fittings-192.987eeafc.webp"
      }
    ]
  },
  "linoleum": {
    "width": 1388,
    "height": 1388,
    "sourceSha": "a0cedcb005e75892",
    "avif": [
      {
        "w": 64,
        "src": "/img/m/linoleum-64.220336a7.avif"
      },
      {
        "w": 96,
        "src": "/img/m/linoleum-96.9adbcff3.avif"
      },
      {
        "w": 128,
        "src": "/img/m/linoleum-128.a26eed8a.avif"
      },
      {
        "w": 192,
        "src": "/img/m/linoleum-192.15764810.avif"
      }
    ],
    "webp": [
      {
        "w": 64,
        "src": "/img/m/linoleum-64.0b6d0398.webp"
      },
      {
        "w": 96,
        "src": "/img/m/linoleum-96.96a7728c.webp"
      },
      {
        "w": 128,
        "src": "/img/m/linoleum-128.b1d01947.webp"
      },
      {
        "w": 192,
        "src": "/img/m/linoleum-192.74a4feaf.webp"
      }
    ]
  },
  "tile": {
    "width": 1327,
    "height": 1327,
    "sourceSha": "8d90ce3dc396cf9d",
    "avif": [
      {
        "w": 64,
        "src": "/img/m/tile-64.f75fc9e4.avif"
      },
      {
        "w": 96,
        "src": "/img/m/tile-96.10329402.avif"
      },
      {
        "w": 128,
        "src": "/img/m/tile-128.92ffdd17.avif"
      },
      {
        "w": 192,
        "src": "/img/m/tile-192.15a1a9d9.avif"
      }
    ],
    "webp": [
      {
        "w": 64,
        "src": "/img/m/tile-64.28d7b914.webp"
      },
      {
        "w": 96,
        "src": "/img/m/tile-96.418f53b8.webp"
      },
      {
        "w": 128,
        "src": "/img/m/tile-128.881377ab.webp"
      },
      {
        "w": 192,
        "src": "/img/m/tile-192.b70f36a5.webp"
      }
    ]
  },
  "grout": {
    "width": 1260,
    "height": 1260,
    "sourceSha": "5005ff80511fca9d",
    "avif": [
      {
        "w": 64,
        "src": "/img/m/grout-64.8db70dbb.avif"
      },
      {
        "w": 96,
        "src": "/img/m/grout-96.25975077.avif"
      },
      {
        "w": 128,
        "src": "/img/m/grout-128.c4cd1167.avif"
      },
      {
        "w": 192,
        "src": "/img/m/grout-192.f1c3e27e.avif"
      }
    ],
    "webp": [
      {
        "w": 64,
        "src": "/img/m/grout-64.1dedfb36.webp"
      },
      {
        "w": 96,
        "src": "/img/m/grout-96.01f1bc6c.webp"
      },
      {
        "w": 128,
        "src": "/img/m/grout-128.9860b3bc.webp"
      },
      {
        "w": 192,
        "src": "/img/m/grout-192.20aaa9bb.webp"
      }
    ]
  }
} as const;
