import type { ToolDef } from "./types";

const room = { kind: "length", unit: "m", min: 300, max: 100_000 } as const;
const tile = { kind: "length", unit: "cm", min: 20, max: 3000 } as const;

/** Tile by piece count (Kerama Marazzi): grid from a corner or the centre, whole and cut tiles, boxes. */
export const plitka: ToolDef = {
  id: "plitka",
  category: "plitka",
  title: "Плитка",
  outcome: "Целые и подрезанные плитки, коробки",
  status: "live",
  fields: [
    { ...room, name: "lengthMm", label: "Длина комнаты", room: "length", main: true, planner: true },
    { ...room, name: "widthMm", label: "Ширина комнаты", room: "width", main: true, planner: true },
    {
      kind: "select",
      name: "surface",
      label: "Что облицовываем",
      main: true,
      dropdown: true,
      options: [
        { value: "floor", label: "Пол" },
        { value: "walls", label: "Стены" },
      ],
    },
    { kind: "preset", label: "Плитка", presets: ["t20", "t30", "t3060", "t60"], main: true },
    {
      kind: "length",
      unit: "m",
      min: 1000,
      max: 10_000,
      name: "heightMm",
      label: "Высота стен",
      room: "height",
      when: { surface: "walls" },
    },
    { kind: "openings", name: "openings", label: "Окна и двери", hint: "Вычитаются, если облицовываем стены" },
    { ...tile, name: "tileLengthMm", label: "Длина плитки", hint: "Вдоль длины комнаты; на стене — по горизонтали" },
    { ...tile, name: "tileWidthMm", label: "Ширина плитки" },
    {
      kind: "number",
      min: 0,
      max: 20,
      step: 0.5,
      unit: "мм",
      name: "jointMm",
      label: "Шов",
      hint: "Стены 1,5–2 мм, пол 2–3 мм",
    },
    {
      kind: "select",
      name: "start",
      label: "Раскладка",
      options: [
        { value: "corner", label: "От угла" },
        { value: "center", label: "От центра" },
      ],
    },
    {
      kind: "select",
      name: "layout",
      label: "Укладка",
      options: [
        { value: "straight", label: "Прямая" },
        { value: "diagonal", label: "Диагональ" },
      ],
    },
    {
      kind: "number",
      min: 0,
      max: 30,
      step: 1,
      unit: "%",
      name: "reservePct",
      label: "Запас",
      hint: "На подрезку и бой",
    },
    {
      kind: "number",
      min: 1,
      max: 200,
      step: 1,
      unit: "шт.",
      name: "tilesPerBox",
      label: "Плиток в коробке",
      hint: "Проверьте на коробке",
    },
    { kind: "toggle", name: "adhesive", label: "Плиточный клей" },
    { kind: "toggle", name: "grout", label: "Затирка" },
    {
      kind: "number",
      min: 3,
      max: 30,
      step: 0.5,
      unit: "мм",
      name: "tileThicknessMm",
      label: "Толщина плитки",
      hint: "Для затирки: глубина шва",
    },
    { kind: "price", item: "tile", name: "price_tile", label: "Цена коробки" },
    { kind: "price", item: "tile-adhesive", name: "price_tile-adhesive", label: "Цена мешка клея" },
    { kind: "price", item: "grout", name: "price_grout", label: "Цена упаковки затирки" },
  ],
  presets: [
    { id: "t20", label: "20 × 20", values: { tileLengthMm: 200, tileWidthMm: 200, tilesPerBox: 25 } },
    { id: "t30", label: "30 × 30", values: { tileLengthMm: 300, tileWidthMm: 300, tilesPerBox: 12 } },
    { id: "t3060", label: "30 × 60", values: { tileLengthMm: 600, tileWidthMm: 300, tilesPerBox: 8 } },
    { id: "t60", label: "60 × 60", values: { tileLengthMm: 600, tileWidthMm: 600, tilesPerBox: 4 } },
  ],
  nextSteps: ["klej", "zatirka"],
  items: {
    tile: { title: "Плитка", photo: "tile" },
    "tile-adhesive": { title: "Плиточный клей", photo: "tile-adhesive" },
    grout: { title: "Затирка", photo: "grout" },
  },
  summary: {
    tiles: "Плиток с запасом",
    whole: "Целых",
    cut: "Подрезанных",
    area: "Площадь облицовки",
    tileArea: "Площадь плитки",
  },
  steps: {
    openings: "Окна и двери закрывают {tiles} целых плиток — их не берём",
    grid: "Раскладка: целых {whole}, подрезанных {cut} — всего {pieces} плиток",
    reserve: "С запасом {pct}% на подрезку и бой: {pieces} → {tiles}",
    diagonal: "Диагональ: {area} м² / {tile} м² + {pct}% = {tiles} плиток",
    boxes: "Коробок по {perBox} шт.: {tiles} / {perBox} → {boxes}",
    adhesive: "Клей — как в калькуляторе клея для этой плитки: {kg} кг, мешков {bags}",
    grout: "Затирка — как в калькуляторе затирки для этого шва и толщины: {kg} кг, упаковок {packs}",
  },
  warnings: {
    openings_exceed_walls: "Окна и двери больше площади стен. Проверьте их размеры",
    narrow_cut: "У края выйдет узкая подрезка {cut} см. Попробуйте раскладку от центра",
  },
  norms: ["tile.reserve", "tile.reserve.diagonal", "tile.perBox", "tile.joint.floor", "tile.joint.wall"],
};
